sudo: required
services:
 - docker

before_install:
 - docker build -t sivametdockid/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true sivametdockid/react-test npm run test

after_success:
 - docker build -t sivametdockid/multi-client ./client
 - docker build -t sivametdockid/multi-nginx  ./nginx
 - docker build -t sivametdockid/multi-server ./server
 - docker build -t sivametdockid/multi-worker ./worker
#Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those image and push them  to docker hub
 - docker push sivametdockid/multi-client
 - docker push sivametdockid/multi-nginx
 - docker push sivametdockid/multi-server
 - docker push sivametdockid/multi-worker
